//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PS_TXN> PS_TXN { get; set; }
        public virtual DbSet<REF_FACILITY_TB> REF_FACILITY_TB { get; set; }
        public virtual DbSet<REF_LOCATION_GROUP_TB> REF_LOCATION_GROUP_TB { get; set; }
        public virtual DbSet<REF_LOCATION_TB> REF_LOCATION_TB { get; set; }
        public virtual DbSet<REF_LOCATION_TYPE_TB> REF_LOCATION_TYPE_TB { get; set; }
        public virtual DbSet<REF_LOCATION_X_LOCATION_GROUP_TB> REF_LOCATION_X_LOCATION_GROUP_TB { get; set; }
        public virtual DbSet<REF_REQUEST_GROUP_TB> REF_REQUEST_GROUP_TB { get; set; }
        public virtual DbSet<REF_REQUEST_TB> REF_REQUEST_TB { get; set; }
        public virtual DbSet<REF_TEST_GROUP_TB> REF_TEST_GROUP_TB { get; set; }
        public virtual DbSet<REF_TEST_TB> REF_TEST_TB { get; set; }
        public virtual DbSet<REF_TEST_X_TEST_GROUP_TB> REF_TEST_X_TEST_GROUP_TB { get; set; }
        public virtual DbSet<REF_WATER_BODY_TB> REF_WATER_BODY_TB { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBL_RECWATER> TBL_RECWATER { get; set; }
        public virtual DbSet<TBL_TEMP_WEATHER_DATA> TBL_TEMP_WEATHER_DATA { get; set; }
        public virtual DbSet<TBL_USER> TBL_USER { get; set; }
        public virtual DbSet<TBL_USER_ROLE> TBL_USER_ROLE { get; set; }
        public virtual DbSet<TRN_RESULT_TB> TRN_RESULT_TB { get; set; }
        public virtual DbSet<TRN_SAMPLE_TB> TRN_SAMPLE_TB { get; set; }
        public virtual DbSet<TRN_SEWER_OVERFLOW_TB> TRN_SEWER_OVERFLOW_TB { get; set; }
        public virtual DbSet<C_SSMA_seq_FACILITY_SEQ> C_SSMA_seq_FACILITY_SEQ { get; set; }
        public virtual DbSet<C_SSMA_seq_LOCATION_GROUP_SEQ> C_SSMA_seq_LOCATION_GROUP_SEQ { get; set; }
        public virtual DbSet<C_SSMA_seq_LOCATION_SEQ> C_SSMA_seq_LOCATION_SEQ { get; set; }
        public virtual DbSet<C_SSMA_seq_LOCATION_TYPE_SEQ> C_SSMA_seq_LOCATION_TYPE_SEQ { get; set; }
        public virtual DbSet<C_SSMA_seq_PS_TXN_SEQ> C_SSMA_seq_PS_TXN_SEQ { get; set; }
        public virtual DbSet<C_SSMA_seq_RECWATER_SEQ> C_SSMA_seq_RECWATER_SEQ { get; set; }
        public virtual DbSet<C_SSMA_seq_REQUEST_GROUP_SEQ> C_SSMA_seq_REQUEST_GROUP_SEQ { get; set; }
        public virtual DbSet<C_SSMA_seq_REQUEST_SEQ> C_SSMA_seq_REQUEST_SEQ { get; set; }
        public virtual DbSet<C_SSMA_seq_RESULTS_SEQ> C_SSMA_seq_RESULTS_SEQ { get; set; }
        public virtual DbSet<C_SSMA_seq_SAMPLE_SEQ> C_SSMA_seq_SAMPLE_SEQ { get; set; }
        public virtual DbSet<C_SSMA_seq_SEWER_OVERFLOW_SEQ> C_SSMA_seq_SEWER_OVERFLOW_SEQ { get; set; }
        public virtual DbSet<C_SSMA_seq_TEST_GROUP_SEQ> C_SSMA_seq_TEST_GROUP_SEQ { get; set; }
        public virtual DbSet<C_SSMA_seq_TEST_SEQ> C_SSMA_seq_TEST_SEQ { get; set; }
        public virtual DbSet<C_SSMA_seq_WATER_BODY_SEQ> C_SSMA_seq_WATER_BODY_SEQ { get; set; }
        public virtual DbSet<TBL_RPT_TEMP_WEATHER> TBL_RPT_TEMP_WEATHER { get; set; }
        public virtual DbSet<TBL_RPT_TEMP_YEARDATE> TBL_RPT_TEMP_YEARDATE { get; set; }
        public virtual DbSet<TBL_TEMP_CSO> TBL_TEMP_CSO { get; set; }
        public virtual DbSet<TBL_TEMP_EXPAND> TBL_TEMP_EXPAND { get; set; }
        public virtual DbSet<TBL_TEMP_MAIN_DETAIL> TBL_TEMP_MAIN_DETAIL { get; set; }
        public virtual DbSet<TBL_WEATHER_DATA> TBL_WEATHER_DATA { get; set; }
        public virtual DbSet<TBL_CHEMISTRY_DATA> TBL_CHEMISTRY_DATA { get; set; }
        public virtual DbSet<TBL_ECOLI_DATA> TBL_ECOLI_DATA { get; set; }
    }
}
