
-- --------------------------------------------------
-- Entity Designer DDL Script for SQL Server 2005, 2008, 2012 and Azure
-- --------------------------------------------------
-- Date Created: 05/13/2016 11:02:30
-- Generated from EDMX file: C:\Users\rburkh\Documents\SVN\EH.WaterQuality\WaterQuality\Models\EHWaterQualityModel.edmx
-- --------------------------------------------------

SET QUOTED_IDENTIFIER OFF;
GO
USE [EH.WaterQuality];
GO
IF SCHEMA_ID(N'dbo') IS NULL EXECUTE(N'CREATE SCHEMA [dbo]');
GO

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[FK__TRN_SAMPL__N_REQ__3DE82FB7]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TRN_SAMPLE_TB] DROP CONSTRAINT [FK__TRN_SAMPL__N_REQ__3DE82FB7];
GO
IF OBJECT_ID(N'[dbo].[FK_LOCATION_X_GROUP_LOCATION_GROUP_N_LOCATION_GROUP_SYSID]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[REF_LOCATION_X_LOCATION_GROUP_TB] DROP CONSTRAINT [FK_LOCATION_X_GROUP_LOCATION_GROUP_N_LOCATION_GROUP_SYSID];
GO
IF OBJECT_ID(N'[dbo].[FK_LOCATION_X_GROUP_LOCATION_N_LOCATION_SYSID]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[REF_LOCATION_X_LOCATION_GROUP_TB] DROP CONSTRAINT [FK_LOCATION_X_GROUP_LOCATION_N_LOCATION_SYSID];
GO
IF OBJECT_ID(N'[dbo].[FK_REF_LOCATION_TB_REF_LOCATION_TYPE_TB_N_LOCATION_TYPE_SYSID]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[REF_LOCATION_TB] DROP CONSTRAINT [FK_REF_LOCATION_TB_REF_LOCATION_TYPE_TB_N_LOCATION_TYPE_SYSID];
GO
IF OBJECT_ID(N'[dbo].[FK_REF_LOCATION_TB_REF_WATER_BODY_TB_N_WATER_BODY_SYSID]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[REF_LOCATION_TB] DROP CONSTRAINT [FK_REF_LOCATION_TB_REF_WATER_BODY_TB_N_WATER_BODY_SYSID];
GO
IF OBJECT_ID(N'[dbo].[FK_REQUEST_LOCATION_GROUP_N_LOCATION_GROUP_SYSID]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[REF_REQUEST_TB] DROP CONSTRAINT [FK_REQUEST_LOCATION_GROUP_N_LOCATION_GROUP_SYSID];
GO
IF OBJECT_ID(N'[dbo].[FK_REQUEST_REQUEST_GROUP_N_REQUEST_GROUP_SYSID]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[REF_REQUEST_TB] DROP CONSTRAINT [FK_REQUEST_REQUEST_GROUP_N_REQUEST_GROUP_SYSID];
GO
IF OBJECT_ID(N'[dbo].[FK_REQUEST_TEST_GROUP_N_TEST_GROUP_SYSID]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[REF_REQUEST_TB] DROP CONSTRAINT [FK_REQUEST_TEST_GROUP_N_TEST_GROUP_SYSID];
GO
IF OBJECT_ID(N'[dbo].[FK_RESULT_SAMPLE_N_SAMPLE_SYSID]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TRN_RESULT_TB] DROP CONSTRAINT [FK_RESULT_SAMPLE_N_SAMPLE_SYSID];
GO
IF OBJECT_ID(N'[dbo].[FK_TBL_CHEMISTRY_DATA_REF_TEST_GROUP_TB]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TBL_CHEMISTRY_DATA] DROP CONSTRAINT [FK_TBL_CHEMISTRY_DATA_REF_TEST_GROUP_TB];
GO
IF OBJECT_ID(N'[dbo].[FK_TBL_ECOLI_DATA_REF_TEST_GROUP_TB]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TBL_ECOLI_DATA] DROP CONSTRAINT [FK_TBL_ECOLI_DATA_REF_TEST_GROUP_TB];
GO
IF OBJECT_ID(N'[dbo].[FK_TEST_GROUP_RECORDS_TEST_N_TEST_SYSID]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[REF_TEST_X_TEST_GROUP_TB] DROP CONSTRAINT [FK_TEST_GROUP_RECORDS_TEST_N_TEST_SYSID];
GO
IF OBJECT_ID(N'[dbo].[FK_TEST_X_GROUP_TEST_GROUP_N_TEST_GROUP_SYSID]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[REF_TEST_X_TEST_GROUP_TB] DROP CONSTRAINT [FK_TEST_X_GROUP_TEST_GROUP_N_TEST_GROUP_SYSID];
GO
IF OBJECT_ID(N'[dbo].[FK_TRN_RESULT_TB_REF_TEST_TB]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TRN_RESULT_TB] DROP CONSTRAINT [FK_TRN_RESULT_TB_REF_TEST_TB];
GO
IF OBJECT_ID(N'[dbo].[FK_TRN_SAMPLE_TB_REF_LOCATION_TB_N_LOCATION_SYSID]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TRN_SAMPLE_TB] DROP CONSTRAINT [FK_TRN_SAMPLE_TB_REF_LOCATION_TB_N_LOCATION_SYSID];
GO
IF OBJECT_ID(N'[dbo].[FK_TRN_SEWER_OVERFLOW_TB_REF_FACILITY_TB]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TRN_SEWER_OVERFLOW_TB] DROP CONSTRAINT [FK_TRN_SEWER_OVERFLOW_TB_REF_FACILITY_TB];
GO
IF OBJECT_ID(N'[dbo].[FK_TRN_SEWER_OVERFLOW_TB_REF_WATER_BODY_TB]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TRN_SEWER_OVERFLOW_TB] DROP CONSTRAINT [FK_TRN_SEWER_OVERFLOW_TB_REF_WATER_BODY_TB];
GO
IF OBJECT_ID(N'[dbo].[FK_USER_ROLE_USER_FK]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TBL_USER_ROLE] DROP CONSTRAINT [FK_USER_ROLE_USER_FK];
GO

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[PS_TXN]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PS_TXN];
GO
IF OBJECT_ID(N'[dbo].[REF_FACILITY_TB]', 'U') IS NOT NULL
    DROP TABLE [dbo].[REF_FACILITY_TB];
GO
IF OBJECT_ID(N'[dbo].[REF_LOCATION_GROUP_TB]', 'U') IS NOT NULL
    DROP TABLE [dbo].[REF_LOCATION_GROUP_TB];
GO
IF OBJECT_ID(N'[dbo].[REF_LOCATION_TB]', 'U') IS NOT NULL
    DROP TABLE [dbo].[REF_LOCATION_TB];
GO
IF OBJECT_ID(N'[dbo].[REF_LOCATION_TYPE_TB]', 'U') IS NOT NULL
    DROP TABLE [dbo].[REF_LOCATION_TYPE_TB];
GO
IF OBJECT_ID(N'[dbo].[REF_LOCATION_X_LOCATION_GROUP_TB]', 'U') IS NOT NULL
    DROP TABLE [dbo].[REF_LOCATION_X_LOCATION_GROUP_TB];
GO
IF OBJECT_ID(N'[dbo].[REF_REQUEST_GROUP_TB]', 'U') IS NOT NULL
    DROP TABLE [dbo].[REF_REQUEST_GROUP_TB];
GO
IF OBJECT_ID(N'[dbo].[REF_REQUEST_TB]', 'U') IS NOT NULL
    DROP TABLE [dbo].[REF_REQUEST_TB];
GO
IF OBJECT_ID(N'[dbo].[REF_TEST_GROUP_TB]', 'U') IS NOT NULL
    DROP TABLE [dbo].[REF_TEST_GROUP_TB];
GO
IF OBJECT_ID(N'[dbo].[REF_TEST_TB]', 'U') IS NOT NULL
    DROP TABLE [dbo].[REF_TEST_TB];
GO
IF OBJECT_ID(N'[dbo].[REF_TEST_X_TEST_GROUP_TB]', 'U') IS NOT NULL
    DROP TABLE [dbo].[REF_TEST_X_TEST_GROUP_TB];
GO
IF OBJECT_ID(N'[dbo].[REF_WATER_BODY_TB]', 'U') IS NOT NULL
    DROP TABLE [dbo].[REF_WATER_BODY_TB];
GO
IF OBJECT_ID(N'[dbo].[TBL_CHEMISTRY_DATA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_CHEMISTRY_DATA];
GO
IF OBJECT_ID(N'[dbo].[TBL_ECOLI_DATA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_ECOLI_DATA];
GO
IF OBJECT_ID(N'[dbo].[TBL_RECWATER]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_RECWATER];
GO
IF OBJECT_ID(N'[dbo].[TBL_TEMP_WEATHER_DATA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_TEMP_WEATHER_DATA];
GO
IF OBJECT_ID(N'[dbo].[TBL_USER]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_USER];
GO
IF OBJECT_ID(N'[dbo].[TBL_USER_ROLE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_USER_ROLE];
GO
IF OBJECT_ID(N'[dbo].[TBL_WEATHER_DATA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_WEATHER_DATA];
GO
IF OBJECT_ID(N'[dbo].[TRN_RESULT_TB]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TRN_RESULT_TB];
GO
IF OBJECT_ID(N'[dbo].[TRN_SAMPLE_TB]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TRN_SAMPLE_TB];
GO
IF OBJECT_ID(N'[dbo].[TRN_SEWER_OVERFLOW_TB]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TRN_SEWER_OVERFLOW_TB];
GO
IF OBJECT_ID(N'[EHWaterQualityModelsEHWaterQualityModelStoreContainer].[TBL_RPT_TEMP_WEATHER]', 'U') IS NOT NULL
    DROP TABLE [EHWaterQualityModelsEHWaterQualityModelStoreContainer].[TBL_RPT_TEMP_WEATHER];
GO
IF OBJECT_ID(N'[EHWaterQualityModelsEHWaterQualityModelStoreContainer].[TBL_RPT_TEMP_YEARDATE]', 'U') IS NOT NULL
    DROP TABLE [EHWaterQualityModelsEHWaterQualityModelStoreContainer].[TBL_RPT_TEMP_YEARDATE];
GO
IF OBJECT_ID(N'[EHWaterQualityModelsEHWaterQualityModelStoreContainer].[TBL_TEMP_CSO]', 'U') IS NOT NULL
    DROP TABLE [EHWaterQualityModelsEHWaterQualityModelStoreContainer].[TBL_TEMP_CSO];
GO
IF OBJECT_ID(N'[EHWaterQualityModelsEHWaterQualityModelStoreContainer].[TBL_TEMP_EXPAND]', 'U') IS NOT NULL
    DROP TABLE [EHWaterQualityModelsEHWaterQualityModelStoreContainer].[TBL_TEMP_EXPAND];
GO
IF OBJECT_ID(N'[EHWaterQualityModelsEHWaterQualityModelStoreContainer].[TBL_TEMP_MAIN_DETAIL]', 'U') IS NOT NULL
    DROP TABLE [EHWaterQualityModelsEHWaterQualityModelStoreContainer].[TBL_TEMP_MAIN_DETAIL];
GO

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'PS_TXN'
CREATE TABLE [dbo].[PS_TXN] (
    [ID] decimal(20,0)  NOT NULL,
    [PARENTID] decimal(20,0)  NULL,
    [COLLID] decimal(10,0)  NOT NULL,
    [CONTENT] varbinary(max)  NULL,
    [CREATION_DATE] datetime  NULL
);
GO

-- Creating table 'REF_FACILITY_TB'
CREATE TABLE [dbo].[REF_FACILITY_TB] (
    [N_FACILITY_SYSID] int IDENTITY(1,1) NOT NULL,
    [SZ_TITLE] varchar(255)  NOT NULL,
    [SZ_ENTERED_BY] nvarchar(256)  NOT NULL,
    [DT_ENTERED] datetime  NOT NULL,
    [SZ_MODIFIED_BY] nvarchar(256)  NOT NULL,
    [DT_MODIFIED] datetime  NOT NULL,
    [B_INACTIVE] bit  NOT NULL,
    [SZ_TIMESTAMP] binary(8)  NOT NULL
);
GO

-- Creating table 'REF_LOCATION_GROUP_TB'
CREATE TABLE [dbo].[REF_LOCATION_GROUP_TB] (
    [N_LOCATION_GROUP_SYSID] int IDENTITY(1,1) NOT NULL,
    [SZ_DESCRIPTION] varchar(255)  NOT NULL,
    [SZ_ENTERED_BY] nvarchar(256)  NOT NULL,
    [DT_ENTERED] datetime  NOT NULL,
    [SZ_MODIFIED_BY] nvarchar(256)  NOT NULL,
    [DT_MODIFIED] datetime  NOT NULL,
    [B_INACTIVE] bit  NOT NULL,
    [SZ_TIMESTAMP] binary(8)  NOT NULL
);
GO

-- Creating table 'REF_LOCATION_TB'
CREATE TABLE [dbo].[REF_LOCATION_TB] (
    [N_LOCATION_SYSID] int IDENTITY(1,1) NOT NULL,
    [SZ_DESCRIPTION] varchar(255)  NOT NULL,
    [N_GIS_X] decimal(16,6)  NULL,
    [N_GIS_Y] decimal(16,6)  NULL,
    [DT_EFFECTIVE] datetime  NULL,
    [DT_EXPIRED] datetime  NULL,
    [N_WATER_BODY_SYSID] int  NULL,
    [SZ_LABEL] varchar(10)  NULL,
    [N_LOCATION_TYPE_SYSID] int  NULL,
    [SZ_STREAM_NUMBER] varchar(5)  NULL,
    [N_LONGITUDE] float  NULL,
    [N_LATITUDE] float  NULL,
    [SZ_SHORT_DESCRIPTION] varchar(30)  NULL,
    [SZ_ENTERED_BY] nvarchar(256)  NOT NULL,
    [DT_ENTERED] datetime  NOT NULL,
    [SZ_MODIFIED_BY] nvarchar(256)  NOT NULL,
    [DT_MODIFIED] datetime  NOT NULL,
    [B_INACTIVE] bit  NOT NULL,
    [SZ_TIMESTAMP] binary(8)  NOT NULL
);
GO

-- Creating table 'REF_LOCATION_TYPE_TB'
CREATE TABLE [dbo].[REF_LOCATION_TYPE_TB] (
    [N_LOCATION_TYPE_SYSID] int IDENTITY(1,1) NOT NULL,
    [SZ_DESCRIPTION] varchar(255)  NOT NULL,
    [SZ_ENTERED_BY] nvarchar(256)  NOT NULL,
    [DT_ENTERED] datetime  NOT NULL,
    [SZ_MODIFIED_BY] nvarchar(256)  NOT NULL,
    [DT_MODIFIED] datetime  NOT NULL,
    [B_INACTIVE] bit  NOT NULL,
    [SZ_TIMESTAMP] binary(8)  NOT NULL
);
GO

-- Creating table 'REF_LOCATION_X_LOCATION_GROUP_TB'
CREATE TABLE [dbo].[REF_LOCATION_X_LOCATION_GROUP_TB] (
    [N_LOCATION_GROUP_SYSID] int IDENTITY(1,1) NOT NULL,
    [N_LOCATION_SYSID] int  NOT NULL,
    [SZ_ENTERED_BY] nvarchar(256)  NOT NULL,
    [DT_ENTERED] datetime  NOT NULL,
    [SZ_MODIFIED_BY] nvarchar(256)  NOT NULL,
    [DT_MODIFIED] datetime  NOT NULL,
    [B_INACTIVE] bit  NOT NULL,
    [SZ_TIMESTAMP] binary(8)  NOT NULL
);
GO

-- Creating table 'REF_REQUEST_GROUP_TB'
CREATE TABLE [dbo].[REF_REQUEST_GROUP_TB] (
    [N_REQUEST_GROUP_SYSID] int IDENTITY(1,1) NOT NULL,
    [SZ_DESCRIPTION] varchar(255)  NOT NULL,
    [SZ_ENTERED_BY] nvarchar(256)  NOT NULL,
    [DT_ENTERED] datetime  NOT NULL,
    [SZ_MODIFIED_BY] nvarchar(256)  NOT NULL,
    [DT_MODIFIED] datetime  NOT NULL,
    [B_INACTIVE] bit  NOT NULL,
    [SZ_TIMESTAMP] binary(8)  NOT NULL
);
GO

-- Creating table 'REF_REQUEST_TB'
CREATE TABLE [dbo].[REF_REQUEST_TB] (
    [N_REQUEST_SYSID] int IDENTITY(1,1) NOT NULL,
    [N_LOCATION_GROUP_SYSID] int  NOT NULL,
    [N_TEST_GROUP_SYSID] int  NOT NULL,
    [N_REQUEST_GROUP_SYSID] int  NOT NULL,
    [SZ_ENTERED_BY] nvarchar(256)  NOT NULL,
    [DT_ENTERED] datetime  NOT NULL,
    [SZ_MODIFIED_BY] nvarchar(256)  NOT NULL,
    [DT_MODIFIED] datetime  NOT NULL,
    [B_INACTIVE] bit  NOT NULL,
    [SZ_TIMESTAMP] binary(8)  NOT NULL
);
GO

-- Creating table 'REF_TEST_GROUP_TB'
CREATE TABLE [dbo].[REF_TEST_GROUP_TB] (
    [N_TEST_GROUP_SYSID] int IDENTITY(1,1) NOT NULL,
    [SZ_DESCRIPTION] varchar(255)  NOT NULL,
    [SZ_ENTERED_BY] nvarchar(256)  NOT NULL,
    [DT_ENTERED] datetime  NOT NULL,
    [SZ_MODIFIED_BY] nvarchar(256)  NOT NULL,
    [DT_MODIFIED] datetime  NOT NULL,
    [B_INACTIVE] bit  NOT NULL,
    [SZ_TIMESTAMP] binary(8)  NOT NULL
);
GO

-- Creating table 'REF_TEST_TB'
CREATE TABLE [dbo].[REF_TEST_TB] (
    [N_TEST_SYSID] int IDENTITY(1,1) NOT NULL,
    [SZ_DESCRIPTION] varchar(255)  NOT NULL,
    [N_MINIMUM_VALUE] decimal(15,6)  NULL,
    [N_MAXIMUM_VALUE] decimal(15,6)  NULL,
    [SZ_LABEL] varchar(30)  NULL,
    [DT_EFFECTIVE] datetime  NULL,
    [DT_EXPIRED] datetime  NULL,
    [SZ_TITLE] varchar(50)  NULL,
    [DT_REQUEST] datetime  NULL,
    [SZ_SAMPLE_MEDIA] varchar(40)  NULL,
    [SZ_SAMPLE_TYPE] varchar(40)  NULL,
    [SZ_ANALYSIS_METHOD] varchar(50)  NULL,
    [SZ_SORT_ORDER] varchar(20)  NULL,
    [SZ_ENTERED_BY] nvarchar(256)  NOT NULL,
    [DT_ENTERED] datetime  NOT NULL,
    [SZ_MODIFIED_BY] nvarchar(256)  NOT NULL,
    [DT_MODIFIED] datetime  NOT NULL,
    [B_INACTIVE] bit  NOT NULL,
    [SZ_TIMESTAMP] binary(8)  NOT NULL
);
GO

-- Creating table 'REF_TEST_X_TEST_GROUP_TB'
CREATE TABLE [dbo].[REF_TEST_X_TEST_GROUP_TB] (
    [N_TEST_GROUP_SYSID] int  NOT NULL,
    [N_TEST_SYSID] int  NOT NULL,
    [SZ_ENTERED_BY] nvarchar(256)  NOT NULL,
    [DT_ENTERED] datetime  NOT NULL,
    [SZ_MODIFIED_BY] nvarchar(256)  NOT NULL,
    [DT_MODIFIED] datetime  NOT NULL,
    [B_INACTIVE] bit  NOT NULL,
    [SZ_TIMESTAMP] binary(8)  NOT NULL
);
GO

-- Creating table 'REF_WATER_BODY_TB'
CREATE TABLE [dbo].[REF_WATER_BODY_TB] (
    [N_WATER_BODY_SYSID] int IDENTITY(1,1) NOT NULL,
    [SZ_NAME] varchar(50)  NOT NULL,
    [SZ_DESCRIPTION] varchar(255)  NOT NULL,
    [SZ_ENTERED_BY] nvarchar(256)  NOT NULL,
    [DT_ENTERED] datetime  NOT NULL,
    [SZ_MODIFIED_BY] nvarchar(256)  NOT NULL,
    [DT_MODIFIED] datetime  NOT NULL,
    [B_INACTIVE] bit  NOT NULL,
    [SZ_TIMESTAMP] binary(8)  NOT NULL
);
GO

-- Creating table 'sysdiagrams'
CREATE TABLE [dbo].[sysdiagrams] (
    [name] nvarchar(128)  NOT NULL,
    [principal_id] int  NOT NULL,
    [diagram_id] int IDENTITY(1,1) NOT NULL,
    [version] int  NULL,
    [definition] varbinary(max)  NULL
);
GO

-- Creating table 'TBL_RECWATER'
CREATE TABLE [dbo].[TBL_RECWATER] (
    [RECWATER_SEQ] int  NOT NULL,
    [RECWATER_DESCRIPTION] varchar(50)  NOT NULL,
    [ENTERED_BY] varchar(50)  NULL,
    [MODIFIED_BY] varchar(50)  NULL,
    [ENTERED_DATETIME] datetime  NULL,
    [MODIFIED_DATETIME] datetime  NULL
);
GO

-- Creating table 'TBL_TEMP_WEATHER_DATA'
CREATE TABLE [dbo].[TBL_TEMP_WEATHER_DATA] (
    [READING_DATE] varchar(20)  NOT NULL,
    [TEMPERATURE_MAX] varchar(20)  NULL,
    [TEMPERATURE_MIN] varchar(20)  NULL,
    [PRECIPITATION_WATER] varchar(20)  NULL,
    [TEMPERATURE_MEAN] varchar(20)  NULL,
    [WINDSPEED_MAX] varchar(20)  NULL,
    [WINDSPEED_DIRECTION] varchar(20)  NULL,
    [READING_DATE_ERR] varchar(100)  NULL,
    [TEMPERATURE_MAX_ERR] varchar(100)  NULL,
    [TEMPERATURE_MIN_ERR] varchar(100)  NULL,
    [PRECIPITATION_WATER_ERR] varchar(100)  NULL,
    [WINDSPEED_MAX_ERR] varchar(100)  NULL,
    [WINDSPEED_DIRECTION_ERR] varchar(100)  NULL,
    [TEMPERATURE_MEAN_ERR] varchar(100)  NULL
);
GO

-- Creating table 'TBL_USER'
CREATE TABLE [dbo].[TBL_USER] (
    [USER_ID] decimal(5,0)  NOT NULL,
    [USER_NAME] varchar(20)  NOT NULL,
    [FULL_NAME] varchar(30)  NULL
);
GO

-- Creating table 'TBL_USER_ROLE'
CREATE TABLE [dbo].[TBL_USER_ROLE] (
    [USER_ID] decimal(5,0)  NOT NULL,
    [PWD] varchar(20)  NOT NULL,
    [USER_ROLE] varchar(20)  NOT NULL
);
GO

-- Creating table 'TRN_RESULT_TB'
CREATE TABLE [dbo].[TRN_RESULT_TB] (
    [N_RESULT_SYSID] int IDENTITY(1,1) NOT NULL,
    [N_RESULT_VALUE] decimal(15,6)  NULL,
    [N_TEST_SYSID] int  NOT NULL,
    [N_SAMPLE_SYSID] int  NOT NULL,
    [SZ_RESULT_VALUE_INDICATOR] char(9)  NULL,
    [SZ_ENTERED_BY] nvarchar(256)  NOT NULL,
    [DT_ENTERED] datetime  NOT NULL,
    [SZ_MODIFIED_BY] nvarchar(256)  NOT NULL,
    [DT_MODIFIED] datetime  NOT NULL,
    [B_INACTIVE] bit  NOT NULL,
    [SZ_TIMESTAMP] binary(8)  NOT NULL,
    [SZ_TEMPERATURE] nvarchar(256)  NULL
);
GO

-- Creating table 'TRN_SAMPLE_TB'
CREATE TABLE [dbo].[TRN_SAMPLE_TB] (
    [N_SAMPLE_SYSID] int IDENTITY(1,1) NOT NULL,
    [N_LOCATION_SYSID] int  NOT NULL,
    [SZ_COLLECTED_BY] varchar(50)  NULL,
    [DT_COLLECTED] datetime  NOT NULL,
    [N_COLLECTED_TIME] varchar(8)  NULL,
    [DT_REQUEST] datetime  NULL,
    [TEMP_RECORDING_ID] float  NULL,
    [SZ_ENTERED_BY] nvarchar(256)  NOT NULL,
    [DT_ENTERED] datetime  NOT NULL,
    [SZ_MODIFIED_BY] nvarchar(256)  NOT NULL,
    [DT_MODIFIED] datetime  NOT NULL,
    [B_INACTIVE] bit  NOT NULL,
    [SZ_TIMESTAMP] binary(8)  NOT NULL,
    [SZ_BATCH_NUMBER] nvarchar(256)  NOT NULL,
    [N_REQUEST_GROUP_SYSID] int  NULL
);
GO

-- Creating table 'TRN_SEWER_OVERFLOW_TB'
CREATE TABLE [dbo].[TRN_SEWER_OVERFLOW_TB] (
    [N_SEWER_OVERFLOW_SYSID] int IDENTITY(1,1) NOT NULL,
    [DT_ACTIVITY_START] datetime  NULL,
    [DT_ACTIVITY_END] datetime  NULL,
    [N_DISCHARGE_GALLONS] decimal(12,0)  NULL,
    [N_WATER_BODY_SYSID] int  NULL,
    [B_CHLORINATE] bit  NULL,
    [B_NPDESCOMP] bit  NULL,
    [SZ_ACTIVITY_TYPE] varchar(6)  NULL,
    [N_DURATION_MINUTES] decimal(6,2)  NULL,
    [N_FACILITY_SYSID] int  NULL,
    [SZ_ACTIVITY_START_TIME] varchar(8)  NULL,
    [SZ_ACTIVITY_END_TIME] varchar(8)  NULL,
    [N_PRECIPITATION] float  NULL,
    [SZ_ENTERED_BY] nvarchar(256)  NOT NULL,
    [DT_ENTERED] datetime  NOT NULL,
    [SZ_MODIFIED_BY] nvarchar(256)  NOT NULL,
    [DT_MODIFIED] datetime  NOT NULL,
    [B_INACTIVE] bit  NOT NULL,
    [SZ_TIMESTAMP] binary(8)  NOT NULL,
    [SZ_CHLORINATE] varchar(7)  NULL,
    [SZ_NPDESCOMP] varchar(7)  NULL
);
GO

-- Creating table 'C_SSMA_seq_FACILITY_SEQ'
CREATE TABLE [dbo].[C_SSMA_seq_FACILITY_SEQ] (
    [id] decimal(38,0) IDENTITY(1,1) NOT NULL
);
GO

-- Creating table 'C_SSMA_seq_LOCATION_GROUP_SEQ'
CREATE TABLE [dbo].[C_SSMA_seq_LOCATION_GROUP_SEQ] (
    [id] decimal(38,0) IDENTITY(1,1) NOT NULL
);
GO

-- Creating table 'C_SSMA_seq_LOCATION_SEQ'
CREATE TABLE [dbo].[C_SSMA_seq_LOCATION_SEQ] (
    [id] decimal(38,0) IDENTITY(1,1) NOT NULL
);
GO

-- Creating table 'C_SSMA_seq_LOCATION_TYPE_SEQ'
CREATE TABLE [dbo].[C_SSMA_seq_LOCATION_TYPE_SEQ] (
    [id] decimal(38,0) IDENTITY(1,1) NOT NULL
);
GO

-- Creating table 'C_SSMA_seq_PS_TXN_SEQ'
CREATE TABLE [dbo].[C_SSMA_seq_PS_TXN_SEQ] (
    [id] decimal(38,0) IDENTITY(1,1) NOT NULL
);
GO

-- Creating table 'C_SSMA_seq_RECWATER_SEQ'
CREATE TABLE [dbo].[C_SSMA_seq_RECWATER_SEQ] (
    [id] decimal(38,0) IDENTITY(1,1) NOT NULL
);
GO

-- Creating table 'C_SSMA_seq_REQUEST_GROUP_SEQ'
CREATE TABLE [dbo].[C_SSMA_seq_REQUEST_GROUP_SEQ] (
    [id] decimal(38,0) IDENTITY(1,1) NOT NULL
);
GO

-- Creating table 'C_SSMA_seq_REQUEST_SEQ'
CREATE TABLE [dbo].[C_SSMA_seq_REQUEST_SEQ] (
    [id] decimal(38,0) IDENTITY(1,1) NOT NULL
);
GO

-- Creating table 'C_SSMA_seq_RESULTS_SEQ'
CREATE TABLE [dbo].[C_SSMA_seq_RESULTS_SEQ] (
    [id] decimal(38,0) IDENTITY(1,1) NOT NULL
);
GO

-- Creating table 'C_SSMA_seq_SAMPLE_SEQ'
CREATE TABLE [dbo].[C_SSMA_seq_SAMPLE_SEQ] (
    [id] decimal(38,0) IDENTITY(1,1) NOT NULL
);
GO

-- Creating table 'C_SSMA_seq_SEWER_OVERFLOW_SEQ'
CREATE TABLE [dbo].[C_SSMA_seq_SEWER_OVERFLOW_SEQ] (
    [id] decimal(38,0) IDENTITY(1,1) NOT NULL
);
GO

-- Creating table 'C_SSMA_seq_TEST_GROUP_SEQ'
CREATE TABLE [dbo].[C_SSMA_seq_TEST_GROUP_SEQ] (
    [id] decimal(38,0) IDENTITY(1,1) NOT NULL
);
GO

-- Creating table 'C_SSMA_seq_TEST_SEQ'
CREATE TABLE [dbo].[C_SSMA_seq_TEST_SEQ] (
    [id] decimal(38,0) IDENTITY(1,1) NOT NULL
);
GO

-- Creating table 'C_SSMA_seq_WATER_BODY_SEQ'
CREATE TABLE [dbo].[C_SSMA_seq_WATER_BODY_SEQ] (
    [id] decimal(38,0) IDENTITY(1,1) NOT NULL
);
GO

-- Creating table 'TBL_RPT_TEMP_WEATHER'
CREATE TABLE [dbo].[TBL_RPT_TEMP_WEATHER] (
    [COLLECTED_DATE] datetime  NOT NULL,
    [TEMP_MAX] float  NULL,
    [TEMP_MIN] float  NULL,
    [TEMP_MEAN] float  NULL,
    [WIND_SPEED_MAX] float  NULL,
    [WIND_SPEED_DIRECTION] float  NULL
);
GO

-- Creating table 'TBL_RPT_TEMP_YEARDATE'
CREATE TABLE [dbo].[TBL_RPT_TEMP_YEARDATE] (
    [START_DATE] datetime  NOT NULL,
    [END_DATE] datetime  NOT NULL
);
GO

-- Creating table 'TBL_TEMP_CSO'
CREATE TABLE [dbo].[TBL_TEMP_CSO] (
    [LOC] varchar(50)  NOT NULL,
    [START_DATE] datetime  NOT NULL,
    [END_DATE] datetime  NULL,
    [START_TIME] varchar(10)  NULL,
    [END_TIME] varchar(10)  NULL,
    [DURATIONS] decimal(6,2)  NULL,
    [VOLUME] float  NOT NULL,
    [REC_WATER] varchar(50)  NOT NULL,
    [CHLORINATE] varchar(1)  NULL,
    [NPDESCOMP] varchar(1)  NULL,
    [SEWER_TYPE] varchar(5)  NULL,
    [PRECIP] float  NULL
);
GO

-- Creating table 'TBL_TEMP_EXPAND'
CREATE TABLE [dbo].[TBL_TEMP_EXPAND] (
    [COLLECTED_DATE] datetime  NOT NULL,
    [COLLECTED_TIME] varchar(8)  NULL,
    [RESULT_VALUE] decimal(15,6)  NULL,
    [TEST_SEQ] float  NOT NULL,
    [LOCATION_SEQ] float  NOT NULL
);
GO

-- Creating table 'TBL_TEMP_MAIN_DETAIL'
CREATE TABLE [dbo].[TBL_TEMP_MAIN_DETAIL] (
    [RECORDING_ID] float  NOT NULL,
    [COLLECTED_DATE] datetime  NOT NULL,
    [COLLECTED_TIME] varchar(20)  NULL,
    [SAMPLE_NBR] decimal(10,2)  NOT NULL,
    [LOCATION_DESC] varchar(4000)  NOT NULL,
    [WATER_TEMP] float  NULL,
    [TEST_TYPE] varchar(4000)  NOT NULL,
    [RESULT] decimal(15,6)  NULL,
    [COLLECTED_BY] varchar(60)  NULL
);
GO

-- Creating table 'TBL_WEATHER_DATA'
CREATE TABLE [dbo].[TBL_WEATHER_DATA] (
    [SZ_READING_DATE] varchar(20)  NOT NULL,
    [SZ_TEMPERATURE_MAX] varchar(20)  NULL,
    [SZ_TEMPERATURE_MIN] varchar(20)  NULL,
    [SZ_PRECIPITATION_WATER] varchar(20)  NULL,
    [SZ_WINDSPEED_MAX] varchar(20)  NULL,
    [SZ_WINDSPEED_DIRECTION] varchar(20)  NULL,
    [SZ_ENTERED_BY] nvarchar(256)  NOT NULL,
    [DT_ENTERED] datetime  NOT NULL,
    [SZ_MODIFIED_BY] nvarchar(256)  NOT NULL,
    [DT_MODIFIED] datetime  NOT NULL,
    [B_INACTIVE] bit  NOT NULL,
    [SZ_TIMESTAMP] binary(8)  NOT NULL,
    [N_SAMPLE_ID] int  NOT NULL
);
GO

-- Creating table 'TBL_CHEMISTRY_DATA'
CREATE TABLE [dbo].[TBL_CHEMISTRY_DATA] (
    [N_CHEMISTRY_SYSID] int IDENTITY(1,1) NOT NULL,
    [SZ_SITE_ID] varchar(10)  NULL,
    [DT_COLLECTED] datetime  NOT NULL,
    [SZ_COLLECTED_TIME] varchar(10)  NULL,
    [SZ_TEST_NAME] varchar(50)  NULL,
    [SZ_SAMPLE_TYPE] varchar(50)  NULL,
    [SZ_SAMPLE_MEDIA] varchar(20)  NULL,
    [SZ_RESULT_VALUE] varchar(20)  NULL,
    [SZ_UNITS] varchar(30)  NULL,
    [SZ_AMETHOD] varchar(80)  NULL,
    [SZ_ENTERED_BY] nvarchar(256)  NOT NULL,
    [DT_ENTERED] datetime  NOT NULL,
    [SZ_MODIFIED_BY] nvarchar(256)  NOT NULL,
    [DT_MODIFIED] datetime  NOT NULL,
    [B_INACTIVE] bit  NOT NULL,
    [SZ_TIMESTAMP] binary(8)  NOT NULL,
    [N_TEST_GROUP_SYSID] int  NOT NULL,
    [SZ_FLAG] varchar(10)  NULL
);
GO

-- Creating table 'TBL_ECOLI_DATA'
CREATE TABLE [dbo].[TBL_ECOLI_DATA] (
    [N_ECOLI_SYSID] int IDENTITY(1,1) NOT NULL,
    [SZ_SITE_ID] varchar(10)  NULL,
    [DT_COLLECTED] datetime  NOT NULL,
    [SZ_COLLECTED_TIME] varchar(10)  NULL,
    [SZ_TEST_NAME] varchar(50)  NULL,
    [SZ_RESULT_VALUE] varchar(20)  NULL,
    [SZ_SAMPLE_TYPE] varchar(50)  NULL,
    [SZ_SAMPLE_MEDIA] varchar(20)  NULL,
    [SZ_UNITS] varchar(30)  NULL,
    [SZ_METHOD] varchar(80)  NULL,
    [SZ_ENTERED_BY] nvarchar(256)  NOT NULL,
    [DT_ENTERED] datetime  NOT NULL,
    [SZ_MODIFED_BY] nvarchar(256)  NOT NULL,
    [DT_MODIFIED] datetime  NOT NULL,
    [B_INACTIVE] bit  NOT NULL,
    [SZ_TIMESTAMP] binary(8)  NOT NULL,
    [N_TEST_GROUP_SYSID] int  NOT NULL,
    [SZ_MODIFIED_BY] nvarchar(256)  NOT NULL,
    [SZ_FLAG] varchar(10)  NULL
);
GO

-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on [ID], [COLLID] in table 'PS_TXN'
ALTER TABLE [dbo].[PS_TXN]
ADD CONSTRAINT [PK_PS_TXN]
    PRIMARY KEY CLUSTERED ([ID], [COLLID] ASC);
GO

-- Creating primary key on [N_FACILITY_SYSID] in table 'REF_FACILITY_TB'
ALTER TABLE [dbo].[REF_FACILITY_TB]
ADD CONSTRAINT [PK_REF_FACILITY_TB]
    PRIMARY KEY CLUSTERED ([N_FACILITY_SYSID] ASC);
GO

-- Creating primary key on [N_LOCATION_GROUP_SYSID] in table 'REF_LOCATION_GROUP_TB'
ALTER TABLE [dbo].[REF_LOCATION_GROUP_TB]
ADD CONSTRAINT [PK_REF_LOCATION_GROUP_TB]
    PRIMARY KEY CLUSTERED ([N_LOCATION_GROUP_SYSID] ASC);
GO

-- Creating primary key on [N_LOCATION_SYSID] in table 'REF_LOCATION_TB'
ALTER TABLE [dbo].[REF_LOCATION_TB]
ADD CONSTRAINT [PK_REF_LOCATION_TB]
    PRIMARY KEY CLUSTERED ([N_LOCATION_SYSID] ASC);
GO

-- Creating primary key on [N_LOCATION_TYPE_SYSID] in table 'REF_LOCATION_TYPE_TB'
ALTER TABLE [dbo].[REF_LOCATION_TYPE_TB]
ADD CONSTRAINT [PK_REF_LOCATION_TYPE_TB]
    PRIMARY KEY CLUSTERED ([N_LOCATION_TYPE_SYSID] ASC);
GO

-- Creating primary key on [N_LOCATION_GROUP_SYSID], [N_LOCATION_SYSID] in table 'REF_LOCATION_X_LOCATION_GROUP_TB'
ALTER TABLE [dbo].[REF_LOCATION_X_LOCATION_GROUP_TB]
ADD CONSTRAINT [PK_REF_LOCATION_X_LOCATION_GROUP_TB]
    PRIMARY KEY CLUSTERED ([N_LOCATION_GROUP_SYSID], [N_LOCATION_SYSID] ASC);
GO

-- Creating primary key on [N_REQUEST_GROUP_SYSID] in table 'REF_REQUEST_GROUP_TB'
ALTER TABLE [dbo].[REF_REQUEST_GROUP_TB]
ADD CONSTRAINT [PK_REF_REQUEST_GROUP_TB]
    PRIMARY KEY CLUSTERED ([N_REQUEST_GROUP_SYSID] ASC);
GO

-- Creating primary key on [N_REQUEST_SYSID] in table 'REF_REQUEST_TB'
ALTER TABLE [dbo].[REF_REQUEST_TB]
ADD CONSTRAINT [PK_REF_REQUEST_TB]
    PRIMARY KEY CLUSTERED ([N_REQUEST_SYSID] ASC);
GO

-- Creating primary key on [N_TEST_GROUP_SYSID] in table 'REF_TEST_GROUP_TB'
ALTER TABLE [dbo].[REF_TEST_GROUP_TB]
ADD CONSTRAINT [PK_REF_TEST_GROUP_TB]
    PRIMARY KEY CLUSTERED ([N_TEST_GROUP_SYSID] ASC);
GO

-- Creating primary key on [N_TEST_SYSID] in table 'REF_TEST_TB'
ALTER TABLE [dbo].[REF_TEST_TB]
ADD CONSTRAINT [PK_REF_TEST_TB]
    PRIMARY KEY CLUSTERED ([N_TEST_SYSID] ASC);
GO

-- Creating primary key on [N_TEST_GROUP_SYSID], [N_TEST_SYSID] in table 'REF_TEST_X_TEST_GROUP_TB'
ALTER TABLE [dbo].[REF_TEST_X_TEST_GROUP_TB]
ADD CONSTRAINT [PK_REF_TEST_X_TEST_GROUP_TB]
    PRIMARY KEY CLUSTERED ([N_TEST_GROUP_SYSID], [N_TEST_SYSID] ASC);
GO

-- Creating primary key on [N_WATER_BODY_SYSID] in table 'REF_WATER_BODY_TB'
ALTER TABLE [dbo].[REF_WATER_BODY_TB]
ADD CONSTRAINT [PK_REF_WATER_BODY_TB]
    PRIMARY KEY CLUSTERED ([N_WATER_BODY_SYSID] ASC);
GO

-- Creating primary key on [diagram_id] in table 'sysdiagrams'
ALTER TABLE [dbo].[sysdiagrams]
ADD CONSTRAINT [PK_sysdiagrams]
    PRIMARY KEY CLUSTERED ([diagram_id] ASC);
GO

-- Creating primary key on [RECWATER_SEQ] in table 'TBL_RECWATER'
ALTER TABLE [dbo].[TBL_RECWATER]
ADD CONSTRAINT [PK_TBL_RECWATER]
    PRIMARY KEY CLUSTERED ([RECWATER_SEQ] ASC);
GO

-- Creating primary key on [READING_DATE] in table 'TBL_TEMP_WEATHER_DATA'
ALTER TABLE [dbo].[TBL_TEMP_WEATHER_DATA]
ADD CONSTRAINT [PK_TBL_TEMP_WEATHER_DATA]
    PRIMARY KEY CLUSTERED ([READING_DATE] ASC);
GO

-- Creating primary key on [USER_ID] in table 'TBL_USER'
ALTER TABLE [dbo].[TBL_USER]
ADD CONSTRAINT [PK_TBL_USER]
    PRIMARY KEY CLUSTERED ([USER_ID] ASC);
GO

-- Creating primary key on [USER_ID], [PWD] in table 'TBL_USER_ROLE'
ALTER TABLE [dbo].[TBL_USER_ROLE]
ADD CONSTRAINT [PK_TBL_USER_ROLE]
    PRIMARY KEY CLUSTERED ([USER_ID], [PWD] ASC);
GO

-- Creating primary key on [N_RESULT_SYSID] in table 'TRN_RESULT_TB'
ALTER TABLE [dbo].[TRN_RESULT_TB]
ADD CONSTRAINT [PK_TRN_RESULT_TB]
    PRIMARY KEY CLUSTERED ([N_RESULT_SYSID] ASC);
GO

-- Creating primary key on [N_SAMPLE_SYSID] in table 'TRN_SAMPLE_TB'
ALTER TABLE [dbo].[TRN_SAMPLE_TB]
ADD CONSTRAINT [PK_TRN_SAMPLE_TB]
    PRIMARY KEY CLUSTERED ([N_SAMPLE_SYSID] ASC);
GO

-- Creating primary key on [N_SEWER_OVERFLOW_SYSID] in table 'TRN_SEWER_OVERFLOW_TB'
ALTER TABLE [dbo].[TRN_SEWER_OVERFLOW_TB]
ADD CONSTRAINT [PK_TRN_SEWER_OVERFLOW_TB]
    PRIMARY KEY CLUSTERED ([N_SEWER_OVERFLOW_SYSID] ASC);
GO

-- Creating primary key on [id] in table 'C_SSMA_seq_FACILITY_SEQ'
ALTER TABLE [dbo].[C_SSMA_seq_FACILITY_SEQ]
ADD CONSTRAINT [PK_C_SSMA_seq_FACILITY_SEQ]
    PRIMARY KEY CLUSTERED ([id] ASC);
GO

-- Creating primary key on [id] in table 'C_SSMA_seq_LOCATION_GROUP_SEQ'
ALTER TABLE [dbo].[C_SSMA_seq_LOCATION_GROUP_SEQ]
ADD CONSTRAINT [PK_C_SSMA_seq_LOCATION_GROUP_SEQ]
    PRIMARY KEY CLUSTERED ([id] ASC);
GO

-- Creating primary key on [id] in table 'C_SSMA_seq_LOCATION_SEQ'
ALTER TABLE [dbo].[C_SSMA_seq_LOCATION_SEQ]
ADD CONSTRAINT [PK_C_SSMA_seq_LOCATION_SEQ]
    PRIMARY KEY CLUSTERED ([id] ASC);
GO

-- Creating primary key on [id] in table 'C_SSMA_seq_LOCATION_TYPE_SEQ'
ALTER TABLE [dbo].[C_SSMA_seq_LOCATION_TYPE_SEQ]
ADD CONSTRAINT [PK_C_SSMA_seq_LOCATION_TYPE_SEQ]
    PRIMARY KEY CLUSTERED ([id] ASC);
GO

-- Creating primary key on [id] in table 'C_SSMA_seq_PS_TXN_SEQ'
ALTER TABLE [dbo].[C_SSMA_seq_PS_TXN_SEQ]
ADD CONSTRAINT [PK_C_SSMA_seq_PS_TXN_SEQ]
    PRIMARY KEY CLUSTERED ([id] ASC);
GO

-- Creating primary key on [id] in table 'C_SSMA_seq_RECWATER_SEQ'
ALTER TABLE [dbo].[C_SSMA_seq_RECWATER_SEQ]
ADD CONSTRAINT [PK_C_SSMA_seq_RECWATER_SEQ]
    PRIMARY KEY CLUSTERED ([id] ASC);
GO

-- Creating primary key on [id] in table 'C_SSMA_seq_REQUEST_GROUP_SEQ'
ALTER TABLE [dbo].[C_SSMA_seq_REQUEST_GROUP_SEQ]
ADD CONSTRAINT [PK_C_SSMA_seq_REQUEST_GROUP_SEQ]
    PRIMARY KEY CLUSTERED ([id] ASC);
GO

-- Creating primary key on [id] in table 'C_SSMA_seq_REQUEST_SEQ'
ALTER TABLE [dbo].[C_SSMA_seq_REQUEST_SEQ]
ADD CONSTRAINT [PK_C_SSMA_seq_REQUEST_SEQ]
    PRIMARY KEY CLUSTERED ([id] ASC);
GO

-- Creating primary key on [id] in table 'C_SSMA_seq_RESULTS_SEQ'
ALTER TABLE [dbo].[C_SSMA_seq_RESULTS_SEQ]
ADD CONSTRAINT [PK_C_SSMA_seq_RESULTS_SEQ]
    PRIMARY KEY CLUSTERED ([id] ASC);
GO

-- Creating primary key on [id] in table 'C_SSMA_seq_SAMPLE_SEQ'
ALTER TABLE [dbo].[C_SSMA_seq_SAMPLE_SEQ]
ADD CONSTRAINT [PK_C_SSMA_seq_SAMPLE_SEQ]
    PRIMARY KEY CLUSTERED ([id] ASC);
GO

-- Creating primary key on [id] in table 'C_SSMA_seq_SEWER_OVERFLOW_SEQ'
ALTER TABLE [dbo].[C_SSMA_seq_SEWER_OVERFLOW_SEQ]
ADD CONSTRAINT [PK_C_SSMA_seq_SEWER_OVERFLOW_SEQ]
    PRIMARY KEY CLUSTERED ([id] ASC);
GO

-- Creating primary key on [id] in table 'C_SSMA_seq_TEST_GROUP_SEQ'
ALTER TABLE [dbo].[C_SSMA_seq_TEST_GROUP_SEQ]
ADD CONSTRAINT [PK_C_SSMA_seq_TEST_GROUP_SEQ]
    PRIMARY KEY CLUSTERED ([id] ASC);
GO

-- Creating primary key on [id] in table 'C_SSMA_seq_TEST_SEQ'
ALTER TABLE [dbo].[C_SSMA_seq_TEST_SEQ]
ADD CONSTRAINT [PK_C_SSMA_seq_TEST_SEQ]
    PRIMARY KEY CLUSTERED ([id] ASC);
GO

-- Creating primary key on [id] in table 'C_SSMA_seq_WATER_BODY_SEQ'
ALTER TABLE [dbo].[C_SSMA_seq_WATER_BODY_SEQ]
ADD CONSTRAINT [PK_C_SSMA_seq_WATER_BODY_SEQ]
    PRIMARY KEY CLUSTERED ([id] ASC);
GO

-- Creating primary key on [COLLECTED_DATE] in table 'TBL_RPT_TEMP_WEATHER'
ALTER TABLE [dbo].[TBL_RPT_TEMP_WEATHER]
ADD CONSTRAINT [PK_TBL_RPT_TEMP_WEATHER]
    PRIMARY KEY CLUSTERED ([COLLECTED_DATE] ASC);
GO

-- Creating primary key on [START_DATE], [END_DATE] in table 'TBL_RPT_TEMP_YEARDATE'
ALTER TABLE [dbo].[TBL_RPT_TEMP_YEARDATE]
ADD CONSTRAINT [PK_TBL_RPT_TEMP_YEARDATE]
    PRIMARY KEY CLUSTERED ([START_DATE], [END_DATE] ASC);
GO

-- Creating primary key on [LOC], [START_DATE], [VOLUME], [REC_WATER] in table 'TBL_TEMP_CSO'
ALTER TABLE [dbo].[TBL_TEMP_CSO]
ADD CONSTRAINT [PK_TBL_TEMP_CSO]
    PRIMARY KEY CLUSTERED ([LOC], [START_DATE], [VOLUME], [REC_WATER] ASC);
GO

-- Creating primary key on [COLLECTED_DATE], [TEST_SEQ], [LOCATION_SEQ] in table 'TBL_TEMP_EXPAND'
ALTER TABLE [dbo].[TBL_TEMP_EXPAND]
ADD CONSTRAINT [PK_TBL_TEMP_EXPAND]
    PRIMARY KEY CLUSTERED ([COLLECTED_DATE], [TEST_SEQ], [LOCATION_SEQ] ASC);
GO

-- Creating primary key on [RECORDING_ID], [COLLECTED_DATE], [SAMPLE_NBR], [LOCATION_DESC], [TEST_TYPE] in table 'TBL_TEMP_MAIN_DETAIL'
ALTER TABLE [dbo].[TBL_TEMP_MAIN_DETAIL]
ADD CONSTRAINT [PK_TBL_TEMP_MAIN_DETAIL]
    PRIMARY KEY CLUSTERED ([RECORDING_ID], [COLLECTED_DATE], [SAMPLE_NBR], [LOCATION_DESC], [TEST_TYPE] ASC);
GO

-- Creating primary key on [SZ_READING_DATE] in table 'TBL_WEATHER_DATA'
ALTER TABLE [dbo].[TBL_WEATHER_DATA]
ADD CONSTRAINT [PK_TBL_WEATHER_DATA]
    PRIMARY KEY CLUSTERED ([SZ_READING_DATE] ASC);
GO

-- Creating primary key on [N_CHEMISTRY_SYSID] in table 'TBL_CHEMISTRY_DATA'
ALTER TABLE [dbo].[TBL_CHEMISTRY_DATA]
ADD CONSTRAINT [PK_TBL_CHEMISTRY_DATA]
    PRIMARY KEY CLUSTERED ([N_CHEMISTRY_SYSID] ASC);
GO

-- Creating primary key on [N_ECOLI_SYSID] in table 'TBL_ECOLI_DATA'
ALTER TABLE [dbo].[TBL_ECOLI_DATA]
ADD CONSTRAINT [PK_TBL_ECOLI_DATA]
    PRIMARY KEY CLUSTERED ([N_ECOLI_SYSID] ASC);
GO

-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on [N_FACILITY_SYSID] in table 'TRN_SEWER_OVERFLOW_TB'
ALTER TABLE [dbo].[TRN_SEWER_OVERFLOW_TB]
ADD CONSTRAINT [FK_TRN_SEWER_OVERFLOW_TB_REF_FACILITY_TB]
    FOREIGN KEY ([N_FACILITY_SYSID])
    REFERENCES [dbo].[REF_FACILITY_TB]
        ([N_FACILITY_SYSID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TRN_SEWER_OVERFLOW_TB_REF_FACILITY_TB'
CREATE INDEX [IX_FK_TRN_SEWER_OVERFLOW_TB_REF_FACILITY_TB]
ON [dbo].[TRN_SEWER_OVERFLOW_TB]
    ([N_FACILITY_SYSID]);
GO

-- Creating foreign key on [N_LOCATION_GROUP_SYSID] in table 'REF_LOCATION_X_LOCATION_GROUP_TB'
ALTER TABLE [dbo].[REF_LOCATION_X_LOCATION_GROUP_TB]
ADD CONSTRAINT [FK_LOCATION_X_GROUP_LOCATION_GROUP_N_LOCATION_GROUP_SYSID]
    FOREIGN KEY ([N_LOCATION_GROUP_SYSID])
    REFERENCES [dbo].[REF_LOCATION_GROUP_TB]
        ([N_LOCATION_GROUP_SYSID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating foreign key on [N_LOCATION_GROUP_SYSID] in table 'REF_REQUEST_TB'
ALTER TABLE [dbo].[REF_REQUEST_TB]
ADD CONSTRAINT [FK_REQUEST_LOCATION_GROUP_N_LOCATION_GROUP_SYSID]
    FOREIGN KEY ([N_LOCATION_GROUP_SYSID])
    REFERENCES [dbo].[REF_LOCATION_GROUP_TB]
        ([N_LOCATION_GROUP_SYSID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_REQUEST_LOCATION_GROUP_N_LOCATION_GROUP_SYSID'
CREATE INDEX [IX_FK_REQUEST_LOCATION_GROUP_N_LOCATION_GROUP_SYSID]
ON [dbo].[REF_REQUEST_TB]
    ([N_LOCATION_GROUP_SYSID]);
GO

-- Creating foreign key on [N_LOCATION_SYSID] in table 'REF_LOCATION_X_LOCATION_GROUP_TB'
ALTER TABLE [dbo].[REF_LOCATION_X_LOCATION_GROUP_TB]
ADD CONSTRAINT [FK_LOCATION_X_GROUP_LOCATION_N_LOCATION_SYSID]
    FOREIGN KEY ([N_LOCATION_SYSID])
    REFERENCES [dbo].[REF_LOCATION_TB]
        ([N_LOCATION_SYSID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_LOCATION_X_GROUP_LOCATION_N_LOCATION_SYSID'
CREATE INDEX [IX_FK_LOCATION_X_GROUP_LOCATION_N_LOCATION_SYSID]
ON [dbo].[REF_LOCATION_X_LOCATION_GROUP_TB]
    ([N_LOCATION_SYSID]);
GO

-- Creating foreign key on [N_LOCATION_TYPE_SYSID] in table 'REF_LOCATION_TB'
ALTER TABLE [dbo].[REF_LOCATION_TB]
ADD CONSTRAINT [FK_REF_LOCATION_TB_REF_LOCATION_TYPE_TB_N_LOCATION_TYPE_SYSID]
    FOREIGN KEY ([N_LOCATION_TYPE_SYSID])
    REFERENCES [dbo].[REF_LOCATION_TYPE_TB]
        ([N_LOCATION_TYPE_SYSID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_REF_LOCATION_TB_REF_LOCATION_TYPE_TB_N_LOCATION_TYPE_SYSID'
CREATE INDEX [IX_FK_REF_LOCATION_TB_REF_LOCATION_TYPE_TB_N_LOCATION_TYPE_SYSID]
ON [dbo].[REF_LOCATION_TB]
    ([N_LOCATION_TYPE_SYSID]);
GO

-- Creating foreign key on [N_WATER_BODY_SYSID] in table 'REF_LOCATION_TB'
ALTER TABLE [dbo].[REF_LOCATION_TB]
ADD CONSTRAINT [FK_REF_LOCATION_TB_REF_WATER_BODY_TB_N_WATER_BODY_SYSID]
    FOREIGN KEY ([N_WATER_BODY_SYSID])
    REFERENCES [dbo].[REF_WATER_BODY_TB]
        ([N_WATER_BODY_SYSID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_REF_LOCATION_TB_REF_WATER_BODY_TB_N_WATER_BODY_SYSID'
CREATE INDEX [IX_FK_REF_LOCATION_TB_REF_WATER_BODY_TB_N_WATER_BODY_SYSID]
ON [dbo].[REF_LOCATION_TB]
    ([N_WATER_BODY_SYSID]);
GO

-- Creating foreign key on [N_LOCATION_SYSID] in table 'TRN_SAMPLE_TB'
ALTER TABLE [dbo].[TRN_SAMPLE_TB]
ADD CONSTRAINT [FK_TRN_SAMPLE_TB_REF_LOCATION_TB_N_LOCATION_SYSID]
    FOREIGN KEY ([N_LOCATION_SYSID])
    REFERENCES [dbo].[REF_LOCATION_TB]
        ([N_LOCATION_SYSID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TRN_SAMPLE_TB_REF_LOCATION_TB_N_LOCATION_SYSID'
CREATE INDEX [IX_FK_TRN_SAMPLE_TB_REF_LOCATION_TB_N_LOCATION_SYSID]
ON [dbo].[TRN_SAMPLE_TB]
    ([N_LOCATION_SYSID]);
GO

-- Creating foreign key on [N_REQUEST_GROUP_SYSID] in table 'REF_REQUEST_TB'
ALTER TABLE [dbo].[REF_REQUEST_TB]
ADD CONSTRAINT [FK_REQUEST_REQUEST_GROUP_N_REQUEST_GROUP_SYSID]
    FOREIGN KEY ([N_REQUEST_GROUP_SYSID])
    REFERENCES [dbo].[REF_REQUEST_GROUP_TB]
        ([N_REQUEST_GROUP_SYSID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_REQUEST_REQUEST_GROUP_N_REQUEST_GROUP_SYSID'
CREATE INDEX [IX_FK_REQUEST_REQUEST_GROUP_N_REQUEST_GROUP_SYSID]
ON [dbo].[REF_REQUEST_TB]
    ([N_REQUEST_GROUP_SYSID]);
GO

-- Creating foreign key on [N_TEST_GROUP_SYSID] in table 'REF_REQUEST_TB'
ALTER TABLE [dbo].[REF_REQUEST_TB]
ADD CONSTRAINT [FK_REQUEST_TEST_GROUP_N_TEST_GROUP_SYSID]
    FOREIGN KEY ([N_TEST_GROUP_SYSID])
    REFERENCES [dbo].[REF_TEST_GROUP_TB]
        ([N_TEST_GROUP_SYSID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_REQUEST_TEST_GROUP_N_TEST_GROUP_SYSID'
CREATE INDEX [IX_FK_REQUEST_TEST_GROUP_N_TEST_GROUP_SYSID]
ON [dbo].[REF_REQUEST_TB]
    ([N_TEST_GROUP_SYSID]);
GO

-- Creating foreign key on [N_TEST_GROUP_SYSID] in table 'REF_TEST_X_TEST_GROUP_TB'
ALTER TABLE [dbo].[REF_TEST_X_TEST_GROUP_TB]
ADD CONSTRAINT [FK_TEST_X_GROUP_TEST_GROUP_N_TEST_GROUP_SYSID]
    FOREIGN KEY ([N_TEST_GROUP_SYSID])
    REFERENCES [dbo].[REF_TEST_GROUP_TB]
        ([N_TEST_GROUP_SYSID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating foreign key on [N_TEST_SYSID] in table 'REF_TEST_X_TEST_GROUP_TB'
ALTER TABLE [dbo].[REF_TEST_X_TEST_GROUP_TB]
ADD CONSTRAINT [FK_TEST_GROUP_RECORDS_TEST_N_TEST_SYSID]
    FOREIGN KEY ([N_TEST_SYSID])
    REFERENCES [dbo].[REF_TEST_TB]
        ([N_TEST_SYSID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TEST_GROUP_RECORDS_TEST_N_TEST_SYSID'
CREATE INDEX [IX_FK_TEST_GROUP_RECORDS_TEST_N_TEST_SYSID]
ON [dbo].[REF_TEST_X_TEST_GROUP_TB]
    ([N_TEST_SYSID]);
GO

-- Creating foreign key on [N_TEST_SYSID] in table 'TRN_RESULT_TB'
ALTER TABLE [dbo].[TRN_RESULT_TB]
ADD CONSTRAINT [FK_TRN_RESULT_TB_REF_TEST_TB]
    FOREIGN KEY ([N_TEST_SYSID])
    REFERENCES [dbo].[REF_TEST_TB]
        ([N_TEST_SYSID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TRN_RESULT_TB_REF_TEST_TB'
CREATE INDEX [IX_FK_TRN_RESULT_TB_REF_TEST_TB]
ON [dbo].[TRN_RESULT_TB]
    ([N_TEST_SYSID]);
GO

-- Creating foreign key on [N_WATER_BODY_SYSID] in table 'TRN_SEWER_OVERFLOW_TB'
ALTER TABLE [dbo].[TRN_SEWER_OVERFLOW_TB]
ADD CONSTRAINT [FK_TRN_SEWER_OVERFLOW_TB_REF_WATER_BODY_TB]
    FOREIGN KEY ([N_WATER_BODY_SYSID])
    REFERENCES [dbo].[REF_WATER_BODY_TB]
        ([N_WATER_BODY_SYSID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TRN_SEWER_OVERFLOW_TB_REF_WATER_BODY_TB'
CREATE INDEX [IX_FK_TRN_SEWER_OVERFLOW_TB_REF_WATER_BODY_TB]
ON [dbo].[TRN_SEWER_OVERFLOW_TB]
    ([N_WATER_BODY_SYSID]);
GO

-- Creating foreign key on [USER_ID] in table 'TBL_USER_ROLE'
ALTER TABLE [dbo].[TBL_USER_ROLE]
ADD CONSTRAINT [FK_USER_ROLE_USER_FK]
    FOREIGN KEY ([USER_ID])
    REFERENCES [dbo].[TBL_USER]
        ([USER_ID])
    ON DELETE CASCADE ON UPDATE NO ACTION;
GO

-- Creating foreign key on [N_SAMPLE_SYSID] in table 'TRN_RESULT_TB'
ALTER TABLE [dbo].[TRN_RESULT_TB]
ADD CONSTRAINT [FK_RESULT_SAMPLE_N_SAMPLE_SYSID]
    FOREIGN KEY ([N_SAMPLE_SYSID])
    REFERENCES [dbo].[TRN_SAMPLE_TB]
        ([N_SAMPLE_SYSID])
    ON DELETE CASCADE ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_RESULT_SAMPLE_N_SAMPLE_SYSID'
CREATE INDEX [IX_FK_RESULT_SAMPLE_N_SAMPLE_SYSID]
ON [dbo].[TRN_RESULT_TB]
    ([N_SAMPLE_SYSID]);
GO

-- Creating foreign key on [N_TEST_GROUP_SYSID] in table 'TBL_CHEMISTRY_DATA'
ALTER TABLE [dbo].[TBL_CHEMISTRY_DATA]
ADD CONSTRAINT [FK_TBL_CHEMISTRY_DATA_REF_TEST_GROUP_TB]
    FOREIGN KEY ([N_TEST_GROUP_SYSID])
    REFERENCES [dbo].[REF_TEST_GROUP_TB]
        ([N_TEST_GROUP_SYSID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TBL_CHEMISTRY_DATA_REF_TEST_GROUP_TB'
CREATE INDEX [IX_FK_TBL_CHEMISTRY_DATA_REF_TEST_GROUP_TB]
ON [dbo].[TBL_CHEMISTRY_DATA]
    ([N_TEST_GROUP_SYSID]);
GO

-- Creating foreign key on [N_TEST_GROUP_SYSID] in table 'TBL_ECOLI_DATA'
ALTER TABLE [dbo].[TBL_ECOLI_DATA]
ADD CONSTRAINT [FK_TBL_ECOLI_DATA_REF_TEST_GROUP_TB]
    FOREIGN KEY ([N_TEST_GROUP_SYSID])
    REFERENCES [dbo].[REF_TEST_GROUP_TB]
        ([N_TEST_GROUP_SYSID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TBL_ECOLI_DATA_REF_TEST_GROUP_TB'
CREATE INDEX [IX_FK_TBL_ECOLI_DATA_REF_TEST_GROUP_TB]
ON [dbo].[TBL_ECOLI_DATA]
    ([N_TEST_GROUP_SYSID]);
GO

-- Creating foreign key on [N_REQUEST_GROUP_SYSID] in table 'TRN_SAMPLE_TB'
ALTER TABLE [dbo].[TRN_SAMPLE_TB]
ADD CONSTRAINT [FK__TRN_SAMPL__N_REQ__3DE82FB7]
    FOREIGN KEY ([N_REQUEST_GROUP_SYSID])
    REFERENCES [dbo].[REF_REQUEST_GROUP_TB]
        ([N_REQUEST_GROUP_SYSID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK__TRN_SAMPL__N_REQ__3DE82FB7'
CREATE INDEX [IX_FK__TRN_SAMPL__N_REQ__3DE82FB7]
ON [dbo].[TRN_SAMPLE_TB]
    ([N_REQUEST_GROUP_SYSID]);
GO

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------