//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_TEST_GROUP_TB
    {
        public REF_TEST_GROUP_TB()
        {
            this.REF_REQUEST_TB = new HashSet<REF_REQUEST_TB>();
            this.REF_TEST_X_TEST_GROUP_TB = new HashSet<REF_TEST_X_TEST_GROUP_TB>();
            this.TBL_CHEMISTRY_DATA = new HashSet<TBL_CHEMISTRY_DATA>();
            this.TBL_ECOLI_DATA = new HashSet<TBL_ECOLI_DATA>();
        }
    
        public int N_TEST_GROUP_SYSID { get; set; }
        public string SZ_DESCRIPTION { get; set; }
        public string SZ_ENTERED_BY { get; set; }
        public System.DateTime DT_ENTERED { get; set; }
        public string SZ_MODIFIED_BY { get; set; }
        public System.DateTime DT_MODIFIED { get; set; }
        public bool B_INACTIVE { get; set; }
        public byte[] SZ_TIMESTAMP { get; set; }
    
        public virtual ICollection<REF_REQUEST_TB> REF_REQUEST_TB { get; set; }
        public virtual ICollection<REF_TEST_X_TEST_GROUP_TB> REF_TEST_X_TEST_GROUP_TB { get; set; }
        public virtual ICollection<TBL_CHEMISTRY_DATA> TBL_CHEMISTRY_DATA { get; set; }
        public virtual ICollection<TBL_ECOLI_DATA> TBL_ECOLI_DATA { get; set; }
    }
}
