//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_LOCATION_TYPE_TB
    {
        public REF_LOCATION_TYPE_TB()
        {
            this.REF_LOCATION_TB = new HashSet<REF_LOCATION_TB>();
        }
    
        public int N_LOCATION_TYPE_SYSID { get; set; }
        public string SZ_DESCRIPTION { get; set; }
        public string SZ_ENTERED_BY { get; set; }
        public System.DateTime DT_ENTERED { get; set; }
        public string SZ_MODIFIED_BY { get; set; }
        public System.DateTime DT_MODIFIED { get; set; }
        public bool B_INACTIVE { get; set; }
        public byte[] SZ_TIMESTAMP { get; set; }
    
        public virtual ICollection<REF_LOCATION_TB> REF_LOCATION_TB { get; set; }
    }
}
