//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_REQUEST_GROUP_TB
    {
        public REF_REQUEST_GROUP_TB()
        {
            this.REF_REQUEST_TB = new HashSet<REF_REQUEST_TB>();
            this.TRN_SAMPLE_TB = new HashSet<TRN_SAMPLE_TB>();
        }
    
        public int N_REQUEST_GROUP_SYSID { get; set; }
        public string SZ_DESCRIPTION { get; set; }
        public string SZ_ENTERED_BY { get; set; }
        public System.DateTime DT_ENTERED { get; set; }
        public string SZ_MODIFIED_BY { get; set; }
        public System.DateTime DT_MODIFIED { get; set; }
        public bool B_INACTIVE { get; set; }
        public byte[] SZ_TIMESTAMP { get; set; }
    
        public virtual ICollection<REF_REQUEST_TB> REF_REQUEST_TB { get; set; }
        public virtual ICollection<TRN_SAMPLE_TB> TRN_SAMPLE_TB { get; set; }
    }
}
