//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_LOCATION_TB
    {
        public REF_LOCATION_TB()
        {
            this.REF_LOCATION_X_LOCATION_GROUP_TB = new HashSet<REF_LOCATION_X_LOCATION_GROUP_TB>();
            this.TRN_SAMPLE_TB = new HashSet<TRN_SAMPLE_TB>();
        }
    
        public int N_LOCATION_SYSID { get; set; }
        public string SZ_DESCRIPTION { get; set; }
        public Nullable<decimal> N_GIS_X { get; set; }
        public Nullable<decimal> N_GIS_Y { get; set; }
        public Nullable<System.DateTime> DT_EFFECTIVE { get; set; }
        public Nullable<System.DateTime> DT_EXPIRED { get; set; }
        public Nullable<int> N_WATER_BODY_SYSID { get; set; }
        public string SZ_LABEL { get; set; }
        public Nullable<int> N_LOCATION_TYPE_SYSID { get; set; }
        public string SZ_STREAM_NUMBER { get; set; }
        public Nullable<double> N_LONGITUDE { get; set; }
        public Nullable<double> N_LATITUDE { get; set; }
        public string SZ_SHORT_DESCRIPTION { get; set; }
        public string SZ_ENTERED_BY { get; set; }
        public System.DateTime DT_ENTERED { get; set; }
        public string SZ_MODIFIED_BY { get; set; }
        public System.DateTime DT_MODIFIED { get; set; }
        public bool B_INACTIVE { get; set; }
        public byte[] SZ_TIMESTAMP { get; set; }
    
        public virtual ICollection<REF_LOCATION_X_LOCATION_GROUP_TB> REF_LOCATION_X_LOCATION_GROUP_TB { get; set; }
        public virtual REF_LOCATION_TYPE_TB REF_LOCATION_TYPE_TB { get; set; }
        public virtual REF_WATER_BODY_TB REF_WATER_BODY_TB { get; set; }
        public virtual ICollection<TRN_SAMPLE_TB> TRN_SAMPLE_TB { get; set; }
    }
}
