//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RPT_TEMP_WEATHER
    {
        public System.DateTime COLLECTED_DATE { get; set; }
        public Nullable<double> TEMP_MAX { get; set; }
        public Nullable<double> TEMP_MIN { get; set; }
        public Nullable<double> TEMP_MEAN { get; set; }
        public Nullable<double> WIND_SPEED_MAX { get; set; }
        public Nullable<double> WIND_SPEED_DIRECTION { get; set; }
    }
}
