//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CHEMISTRY_DATA
    {
        public int N_CHEMISTRY_SYSID { get; set; }
        public string SZ_SITE_ID { get; set; }
        public System.DateTime DT_COLLECTED { get; set; }
        public string SZ_COLLECTED_TIME { get; set; }
        public string SZ_TEST_NAME { get; set; }
        public string SZ_SAMPLE_TYPE { get; set; }
        public string SZ_SAMPLE_MEDIA { get; set; }
        public string SZ_RESULT_VALUE { get; set; }
        public string SZ_UNITS { get; set; }
        public string SZ_AMETHOD { get; set; }
        public string SZ_ENTERED_BY { get; set; }
        public System.DateTime DT_ENTERED { get; set; }
        public string SZ_MODIFIED_BY { get; set; }
        public System.DateTime DT_MODIFIED { get; set; }
        public bool B_INACTIVE { get; set; }
        public byte[] SZ_TIMESTAMP { get; set; }
        public int N_TEST_GROUP_SYSID { get; set; }
        public string SZ_FLAG { get; set; }
    
        public virtual REF_TEST_GROUP_TB REF_TEST_GROUP_TB { get; set; }
    }
}
