//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RPT_TEMP_YEARDATE
    {
        public System.DateTime START_DATE { get; set; }
        public System.DateTime END_DATE { get; set; }
    }
}
