//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TEMP_WEATHER_DATA
    {
        public string READING_DATE { get; set; }
        public string TEMPERATURE_MAX { get; set; }
        public string TEMPERATURE_MIN { get; set; }
        public string PRECIPITATION_WATER { get; set; }
        public string TEMPERATURE_MEAN { get; set; }
        public string WINDSPEED_MAX { get; set; }
        public string WINDSPEED_DIRECTION { get; set; }
        public string READING_DATE_ERR { get; set; }
        public string TEMPERATURE_MAX_ERR { get; set; }
        public string TEMPERATURE_MIN_ERR { get; set; }
        public string PRECIPITATION_WATER_ERR { get; set; }
        public string WINDSPEED_MAX_ERR { get; set; }
        public string WINDSPEED_DIRECTION_ERR { get; set; }
        public string TEMPERATURE_MEAN_ERR { get; set; }
    }
}
