//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER
    {
        public TBL_USER()
        {
            this.TBL_USER_ROLE = new HashSet<TBL_USER_ROLE>();
        }
    
        public decimal USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string FULL_NAME { get; set; }
    
        public virtual ICollection<TBL_USER_ROLE> TBL_USER_ROLE { get; set; }
    }
}
