//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RECWATER
    {
        public int RECWATER_SEQ { get; set; }
        public string RECWATER_DESCRIPTION { get; set; }
        public string ENTERED_BY { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> ENTERED_DATETIME { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATETIME { get; set; }
    }
}
