//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_SAMPLE_TB
    {
        public TRN_SAMPLE_TB()
        {
            this.TRN_RESULT_TB = new HashSet<TRN_RESULT_TB>();
        }
    
        public int N_SAMPLE_SYSID { get; set; }
        public int N_LOCATION_SYSID { get; set; }
        public string SZ_COLLECTED_BY { get; set; }
        public System.DateTime DT_COLLECTED { get; set; }
        public string N_COLLECTED_TIME { get; set; }
        public Nullable<System.DateTime> DT_REQUEST { get; set; }
        public Nullable<double> TEMP_RECORDING_ID { get; set; }
        public string SZ_ENTERED_BY { get; set; }
        public System.DateTime DT_ENTERED { get; set; }
        public string SZ_MODIFIED_BY { get; set; }
        public System.DateTime DT_MODIFIED { get; set; }
        public bool B_INACTIVE { get; set; }
        public byte[] SZ_TIMESTAMP { get; set; }
        public string SZ_BATCH_NUMBER { get; set; }
        public Nullable<int> N_REQUEST_GROUP_SYSID { get; set; }
    
        public virtual REF_LOCATION_TB REF_LOCATION_TB { get; set; }
        public virtual ICollection<TRN_RESULT_TB> TRN_RESULT_TB { get; set; }
        public virtual REF_REQUEST_GROUP_TB REF_REQUEST_GROUP_TB { get; set; }
    }
}
